use 'certifi' certificates in fetch_pandas_versions script (#18588)
We've recently observed CI jobs that run `ci/cudf_pandas_scripts/fetch_pandas_versions.py` failing like this:

```text
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1017)
```

([build link](https://github.com/rapidsai/cudf/actions/runs/14634763474/job/41082559278#step:10:813))

Rebuilding the CI docker images did not fix this. I'm still not sure what the root cause it, but it looks like using the certificates delivered by `certifi` (https://pypi.org/project/certifi/) fixes the problem. In my experience, those tend to be updated more quickly than Rocky Linux 8 updates its `ca-certificates` package.

## Notes for Reviewers

#

Authors:
  - James Lamb (https://github.com/jameslamb)

Approvers:
  - Vyas Ramasubramani (https://github.com/vyasr)
  - Bradley Dice (https://github.com/bdice)
  - David Wendt (https://github.com/davidwendt)
  - Matthew Roeschke (https://github.com/mroeschke)

URL: https://github.com/rapidsai/cudf/pull/18588