Fix `print()` keyword argument in cudf pandas test (#18513)
Not sure if this test is running in CI, but `print()` doesn't have an `out=` keyword argument:

```shell
$ python
Python 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print("hello", out=sys.stderr)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'out' is an invalid keyword argument for print()
>>> print("hello", file=sys.stderr)
hello
```

Authors:
  - Paul Taylor (https://github.com/trxcllnt)

Approvers:
  - Vyas Ramasubramani (https://github.com/vyasr)

URL: https://github.com/rapidsai/cudf/pull/18513