[BUG] Set `query_set` arg when validating/running cudf-polars PDS-DS benchmarks (#19674)
Follows up https://github.com/rapidsai/cudf/pull/19631. I didn't set the set `query_set` (ie. the benchmark name `pdsh` or `pdsds`) arg when running the PDS-DS benchmarks in validation mode (ie. `--engine validate`) or the DuckDB benchmarks (ie. `--engine duckdb`). Therefore we'd get this error
```
$ python python/cudf_polars/cudf_polars/experimental/benchmarks/pdsds.py --engine duckdb 12 --root tpcds_parquet --scale 1.0
Traceback (most recent call last):
  File "/home/coder/cudf/python/cudf_polars/cudf_polars/experimental/benchmarks/pdsds.py", line 218, in <module>
    run_duckdb(PDSDSDuckDBQueries, extra_args)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coder/cudf/python/cudf_polars/cudf_polars/experimental/benchmarks/pdsds.py", line 109, in run_duckdb
    run_config = RunConfig.from_args(args)
  File "/home/coder/cudf/python/cudf_polars/cudf_polars/experimental/benchmarks/utils.py", line 216, in from_args
    name = args.query_set
           ^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'query_set'
```
This PR fixes this error.

Authors:
  - Matthew Murray (https://github.com/Matt711)

Approvers:
  - Matthew Roeschke (https://github.com/mroeschke)

URL: https://github.com/rapidsai/cudf/pull/19674